---

  - name: play for all servers
    hosts: all
    become: true

    tasks:
      - name: update yum  repo
        yum:
          name: "*"
          state: latest
          update_cache: yes

      - name: install nfs client, chrony
        yum: 
          name: "{{ item }}"
          state: present
        loop: 
          - nfs-utils
          - chrony
          - httpd
        tags:
          - always

      - name: start and enable
        service: 
          name: chronyd
          enabled: yes
          state: started 

      - name: install mysql
        yum:
          name: mysql-server
          state: present
        notify:
          - start and enable mysql

      - name: start and enable httpd
        service: 
          name: httpd
          enabled: yes
          state: started

    handlers:
      - name: start and enable mysql
        service: 
          name: mysqld
          enabled: yes
          state: started
        tags:
          - always 


          


      



